#!/bin/bash

# Scripts path
assegai_path=$(which assegai)
assegai_path=${assegai_path:0:-7}
src_dir="${assegai_path}src/"

function cleanup()
{
  tput cnorm
}

trap cleanup EXIT

php "${src_dir}index.php" "${@:1}"
